#!/bin/sh

$HOME/.config/polybar/launch.sh &
xrdb -merge ~/.Xresources &
sxhkd &
killall picom; picom &
nitrogen --restore &
betterlockscreen -u /home/rasum/Pictures/lock.jpg &

bspc monitor eDP-1 -d I II III IV V VI VII VIII
bspc monitor HDMI-1 -d VIII IX X

# bspwm configuration
# *******************

#bspc config border_radius		10
bspc config initial_polarity 		second_child
bspc config pointer_modifier 		mod4
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner
bspc config click_to_focus 		true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config merge_overlapping_monitors 	true
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	true
bspc config history_aware_focus		true
bspc config top_padding			0
bspc config bottom_padding 		0
bspc config left_padding 		0
bspc config right_padding 		0
bspc config border_width		1
bspc config window_gap 			15

# bspwm coloring
# **************
bspc config active_border_color "#333333"
bspc config normal_border_color "#080a1c"
bspc config focused_border_color "#0066cc"
bspc config presel_feedback_color "#5e81ac"

# rules
# *****

bspc rule -a firefox desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr
